name: geo_surveys_app
description: "Mobile app for geocontrol surveys"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  camera: ^0.11.2
  dio: ^5.9.0
  drift: ^2.29.0
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  path_provider: ^2.1.5
  provider: ^6.1.5
  yandex_maps_mapkit_lite: ^4.26.1-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
