name: geo_surveys_app
description: "Mobile app for geocontrol surveys"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  aws_s3_api: ^2.0.0
  bcrypt: ^1.1.3
  camera: ^0.11.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  path_provider: ^2.1.5
  postgres: ^3.5.7
  provider: ^6.1.5
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
