name: geo_surveys_app
description: "Mobile app for geocontrol surveys"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  camera: ^0.11.2
  dio: ^5.9.0
  drift: ^2.29.0
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  flutter_map_marker_cluster: ^8.2.2
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5

dev_dependencies:
  lint: ^2.8.0
  dart_code_linter: ^3.2.1

flutter:
  uses-material-design: true
